## Servers
server:
  port: 3000

## Spring
spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
    platform: oauth2-h2
    #    url: jdbc:mariadb://192.168.79.130:3306/testdb?useSSL=false&useUnicode=true&characterEncoding=utf8&seLegacyDatetimeCode=false
    #    username: tester
    #    password: tester
    #    driver-class-name: org.mariadb.jdbc.Driver
    #    platform: oauth2-maria
    initialization-mode: always
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        #dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop

## Application
app:
  admin-username: admin@email.com
  admin-password: admin
  user-username: user@gmail.com
  user-password: user
  client-id: application
  client-secret: pass
  swagger:
    accessTokenUri: http://localhost:3000/oauth/token
